export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";

export const GET_ADMIN_DETAILS_REQUEST = "GET_ADMIN_DETAILS_REQUEST";
export const GET_ADMIN_DETAILS_SUCCESS = "GET_ADMIN_DETAILS_SUCCESS";
export const GET_ADMIN_DETAILS_FAILURE = "GET_ADMIN_DETAILS_FAILURE";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
