export const ADD_EXPERIENCE_STORIES_REQUEST = "ADD_EXPERIENCE_STORIES_REQUEST";
export const ADD_EXPERIENCE_STORIES_SUCCESS = "ADD_EXPERIENCE_STORIES_SUCCESS";
export const ADD_EXPERIENCE_STORIES_FAILURE = "ADD_EXPERIENCE_STORIES_FAILURE";

export const GET_ALL_EXPERIENCES_REQUEST = "GET_ALL_EXPERIENCES_REQUEST";
export const GET_ALL_EXPERIENCES_SUCCESS = "GET_ALL_EXPERIENCES_SUCCESS";
export const GET_ALL_EXPERIENCES_FAILURE = "GET_ALL_EXPERIENCES_FAILURE";

export const UPDATE_EXPERIENCE_STORIES_REQUEST =
  "UPDATE_EXPERIENCE_STORIES_REQUEST";
export const UPDATE_EXPERIENCE_STORIES_SUCCESS =
  "UPDATE_EXPERIENCE_STORIES_SUCCESS";
export const UPDATE_EXPERIENCE_STORIES_FAILURE =
  "UPDATE_EXPERIENCE_STORIES_FAILURE";
